### ISSUE TITLE
Q1/Q2 Roadmap

### ISSUE THREAD

**Issue by parkan** [mediachain/L-SPACE#21]
## Proof of Concept
- [x] Complete rudimentary graph ops
- [x] Open source L-SPACE
- [ ] Pilot dataset import prep
  - [x] Manual tree merge (root pointer) (#16)
  - [x] Schema translator (ad-hoc) (#17)
  - [x] Basic signing (single authoritative pkey list) (#13)
  - [ ] Naive duplicate detection (filtered exact string match) (#19)
  - [ ] HEAD pointer/reconciled metadata calculation (naive) (#20)
- [ ] Graph visualization (#15)
- [ ] Basic UI
- [ ] Weekly/daily graph data dumps (#14)
- [ ] Basic API (#18)

## Phase II
- [ ] Schema translator DSL continued
- [ ] Search/indexing
  - [ ] Text search (Solr? Elastic?)
  - [ ] Perceptual resolver (pastec)
- [ ] Improved merging

- [ ] expanded/3rd-party usable API
- [ ] Publish to IPLD (decentralized read)

## Phase III
- Performance improvement: additional caching layers, "good enough" answers
- Key management/identity/reputation
- Machine learn reconciliation
- Decentralized writes
