### ISSUE TITLE
DPLA Demo Checklist

### ISSUE THREAD

**Issue by parkan** [mediachain/L-SPACE#58]
- [x] Find at least one item with 2+ "revisions". This could be **A)** two different institutions (jresig ukiyo-e style, preferred) or **B)** one institution that has made revisions *BONUS: BOTH!*
- [x] Find a good author that is present in both institutions' collections
  - [x] Pick something good conceptually (Picasso is my default)
  - [ ] Verify that matching happened automatically in existing ingestion (@bigs)
- [x] Set up .env/ssh access to OrientDB machine for @denisnazarov + @yusefnapora + @parkan
- [x] Output RawMetadataBlob for every matching statement (optionally)
- [x] Output "IPFS address" hash (provisionally)
- [ ] Finish endpoints:
  - [x] single canonical + first blob
  - [x] revision history
  - [x] all canonicals
  - [ ] ~~possibly "dumb" search (full scan)~~

**Comment by parkan** [comment]
Ok *lots* of revisions in here https://github.com/parkan/collection-sans-turner/commit/f60339d97b379f5412dada56d07f9d596033a275

However, because we've imported the latest HEAD we can't just apply these on top so we need to pick one entry, delete its current tree and reimport some revisions on top.

**Comment by parkan** [comment]
Taking search off the table, don't think we'll have time

@denisnazarov can you post your findings here?

**Comment by denisnazarov** [comment]
@parkan This Durer is fairly famous and seems like a good example:

https://www.rijksmuseum.nl/en/collection/RP-P-OB-66.803
http://collection.britishmuseum.org/resource?uri=http://collection.britishmuseum.org/id/object/PPA42171

BritishMusem has a link to get the JSON, Rijks may require getting an API key but there might be a dump somewhere.

**Comment by parkan** [comment]
Sadly the british museum json is crazy RDF and we're not prepared to parse it right now @denisnazarov

**Comment by denisnazarov** [comment]
Cartier-Bresson:

http://www.moma.org/collection/works/44586?locale=en
http://www.tate.org.uk/art/artworks/cartier-bresson-hyeres-france-p13112

http://www.icp.org/browse/archive/objects/hy%C3%A8res-france
http://www.magnumphotos.com/C.aspx?VP3=SearchResult&ALID=2K7O3R14TE52

**Comment by denisnazarov** [comment]
i think HCB above is better, but here's another suggestion from richard in DH slack:

http://collections.vam.ac.uk/item/O78889/strawberry-thief-furnishing-fabric-morris-william/
http://www.moma.org/collection/works/4530?locale=en
